### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by gastonframirez** [MaGa-UBP/UBP-PDC#2]
Organizar el home y maquetar

**Comment by gastonframirez** [comment]
Se me ocurre en esta parte:
<img width="1440" alt="screen shot 2018-04-02 at 7 00 34 pm" src="https://user-images.githubusercontent.com/5036728/38218439-32c4bf76-36a8-11e8-9194-739bfd1f3fcf.png">
Hacer algo con 3 iconos y ponerle algun efecto de [estos](https://daneden.github.io/animate.css/) (ej: pulse), y que esas 3 columnas digan fun facts o algo asi de Islandia

**Comment by makpar** [comment]
Dale, me parece perfecto, aca hay unos links para elegir los 3 o 4 fun facts mas copados:
https://www.dangerous-business.com/2012/03/14-fun-facts-about-iceland/
https://icelandmonitor.mbl.is/news/news/2017/01/29/20_strange_and_awesome_facts_about_iceland/

**Comment by makpar** [comment]
Acordarse de poner la bandera
