### ISSUE TITLE
Cuestionario

### ISSUE THREAD

**Issue by gastonframirez** [MaGa-UBP/UBP-PDC#3]
Cestionario con 10 preguntas incluyendo:

- 4 (cuatro) preguntas con una única opción de respuesta
- 4 (cuatro) preguntas con varias opciones de respuesta
- 2 (dos) preguntas por porcentaje/puntaje de respuesta

El cuestionario deberá solicitar nombre, edad y correo del usuario que responde.
Agregar un botón "Finalizar" que cuando el usuario lo presione, haciendo uso de jQuery, se verifiquen y marquen las respuestas correctas e incorrectas que haya respondido el usuario, a la vez, de enviar los datos ingresados por correo electrónico.

Hagamos en este ticket la lista de preguntas que queremos hacer.

**Comment by makpar** [comment]
Preguntas con única opción:
1. Cual es una de las actividades favoritas de los habitantes de Reykjavik y que define su modo de vida?
a) Esquiar por las montanas del norte.
b) Comer Hot Dogs mirando el mar.
c) Ir a una piscina publica. --> Esta es la correcta
d) Ir a un café y hablar de política.

2. Cual es el nombre del salto famoso que se encuentra en los fiordos del oeste de Islandia?
a) Látrabjarg 
b) Hornbjarg
c) Vigur
d) Dynjandi --> esta es la correcta

3. Cuantos cm al año se alejan las placas continentales de Eurasia y América?
a) 2 cm --> esta es la correcta
b) 0,5 cm
c) 5 cm
d) 1 cm

4. Cuantas veces ha entrado en erupcion el volcan Hekla?
a) 5
b) 20 --> correcta
c) 0
d) 8

Preguntas con varias opciones de respuesta:
1. Cuales son las 3 religiones mas populares en Islandia?
- Iglesia Luterana --> correcta
- Judaismo
- Catolicismo
- Iglesia de Islandia --> correcta
- Iglesia Luterana Libre -->correcta

2. To be continued...

**Comment by gastonframirez** [comment]
Sigo con las preguntas con varias opciones de respuesta:
2. Qué idiomas son obligatorios estudiar? (lo saqué de [acá](https://es.wikipedia.org/wiki/Islandia#Idioma))
- Inglés --> correcta
- Alemán
- Noruego
- Danés --> correcta
- Sueco


3. Qué colores están presentes en la bandera de Islandia? (esta es medio chamullo, pero si no encontramos una mejor la usamos jajaja)
- Rojo --> correcta
- Amarillo
- Blanco --> correcta
- Azul --> correcta

4. Que fuentes de energía proveen la electricidad a toda la isla? (lo saqué de [acá](https://es.wikipedia.org/wiki/Islandia#Energ%C3%ADa)
- Geotérmica --> correcta
- Hidráulica --> correcta
- Nuclear
- Combustibles Fósiles


Preguntas de porcentaje:
1. Qué porcentaje de la población pertenece a la Iglesia de Islandia? --> 90%
2. Qué porcentaje del país está cubierto por glaciares? --> 11%
